---
title: "Vitenskapsfilosofi"
format: pdf
bibliography: referanser.bib
---

### 1.

Hvilken forbindelse det er mellom en observasjon og teori som gjør det mulig for oss å trekke slutninger i teorien basert på observasjonene, regnes som et grunnleggende problem i vitenskapsfilosofien [@godfrey-smith2003]. Innledningsvis ønsker jeg å gi en forklaring av begrepet induksjon. Begrepet innebærer at hva som har skjedd kan sies å være forutsigende for hva som vil skje i framtiden. Samtidig innebærer det muligheten til å generalisere et observert resultat fra tidligere [@glass2010].

Ifølge David Hume vil et hvert induktivt argument forutsette uniformitetsprinsippet, ofte et skjult premiss ved induktive argumenter at fremtiden vil alltid være lik som fortiden. Videre argumenterte han at dette prinsippet ikke har noen rasjonell begrunnelse og dermed har heller ingen av konklusjonene fra disse argumentene noen rasjonell begrunnelse [@vassend2023a]. Han mente at vi ikke kunne bruke fortiden til å predikere fremtiden. Fra et empiristisk syn som Hume representerte så vil det å være rasjonell si å empirisk teste faktapåstander. Videre skal jeg diskutere om konklusjonen til Hume kan være mulig å unngå.

For å belyse dette trekker jeg fram et eksempel fra @stove1965 . Dette er en flamme, en flamme har vært varm tidligere, derfor må også denne flammen være varm [@stove1965]. Her har vi et premiss for å anta at denne flammen også er varm, nettopp om at fremtiden vil være som fortiden. Prinsippet er noe vi ikke nødvendigvis tenker over, men den må være der for at vi skal kunne trekke antagelsen om flammen. Uniformitetsprinsippet kan ikke bevises gjennom logikk, og faktisk så er det jo heller slik at det er lett å forestille seg at fremtiden gjerne er forskjellig fra fortiden [@vassend2023b]. Premisset ser ikke ut til å være mulig å bevises til å være sant eller usant. I tillegg har vi en ny antagelse om at uniformitetsprinsippet er sant for at argumentene våre skal være bra. Med andre ord så ser vi ikke ut til å ha kommet utenom induksjon fordi vi er nødt til å forutsette at fremtiden er lik som fortiden, og bruker tidligere observasjoner til å si at det er slik.

Du kommer ikke utenom Hume sitt argument. Men likevel er det praktisk for oss mennesker å godta denne usikkerheten. Det er heller ikke irrasjonelt å godta uniformitetsprinsippet [@stove1965]. Men kanskje kan det faktum at det heller ikke kan sies å være irrasjonelt faktisk gjør at du rasjonelt kan begrunne bruken av induksjon? Og Popper var tross alt heller ikke imot at vi brukte det i dagliglivet [@godfrey-smith2003]. Likevel er det det at vi ikke kan blande følelser som er rasjonelt med vitenskap. Og selv med nye tilnærminger så klarer vi ikke komme helt utenom induksjon. Så vi klarer ikke helt å unngå Hume sin konklusjon, selv om det i vitenskapen kan være praktisk å godta visse premisser.

### 2.

Til kontrast fra Hume og induksjonsproblemet så var det senere en annen vitenskapsfilosof, Karl Popper, som introduserte falsifikasjonisme. Problemet var å skille hva som var vitenskap fra hva som ikke var vitenskap, og Popper sin løsning på dette problemet ga han navnet falsifikasjonisme [@godfrey-smith2003]. Løsningen til Popper bygger på at selv om man ikke kan bevise om noe kommer til å skje, så kan man med sikkerhet si om noe faktisk skjedde eller ikke [@popper1982]. Falsifikasjonisme sier videre at bekreftelse er en myte, og at man bare kan bekrefte noe basert på å motbevise at noe ikke stemmer [@godfrey-smith2003]. Ifølge Popper var induktive resonnementer en fiasko, men at logikk derimot var en god teori [@vassend2023b].

Hypoteser skal testes og man skal prøve å falsifisere dem. Klarer man ikke å falsifisere hypotesen holder den stand og man styrker teorien sin. Helt til man får falsifisert den, da må man justere på teorien man hadde. En teori er bedre hvis den er mer falsifiserbar, for å være det må den være presis [@vassend2023b]. Det er nettopp det at man kan falsifisere en hypotese med observasjoner som skiller et vitenskapelig spørsmål fra spørsmål som ikke er vitenskapelige ifølge Popper.

Problemet som oppstår er at for å falsifisere noe så trenger du en bekreftelse, noe som bare er mulig ved induksjon. For å bekrefte noe må du basert på tidligere observasjoner, stole på det du har sett tidligere, samt at det kan brukes til å si bekrefte. Vi har alstå et stort problem; det er i mange tilfeller nødvendig med induksjon for å falsifisere. Induksjonsproblemet er nettopp årsaken til at Popper ga opp induksjon og forkastet det helt [@vassend2023b]. Dette problemet beskriver også Popper selv [@godfrey-smith2003].

For å forklare tydeligere hva som menes kan vi bruke Newton sin lov om tyngdekraft, F = ma. Her må man anta at tyngdekraften er konstant, og vi er i gang med antagelser. Luftmotstanden er konstant, ny antagelse nok en gang. Her er det involvert støttehypoteser som må være der for at teorien skal være riktig. Duhem hadde et logisk poeng om at dersom det predikerte resultatet skulle vise seg å være feil, så må det bety at alle støttehypoteser og teori er feil fordi dette er det eneste logiske. Enten er teorien feil, eller så er hjelpehypotesene feil. Problemet i dette tilfellet blir at man må bekrefte at hjelpehypotesene er sanne og at det dermed er teorien som er feil, eller så er det noe feil med observasjonen vi har gjort. Vi har igjen induksjon [@vassend2023b].

Hvis vi ser for oss en situasjon der du har to alternativer. En som er blitt prøvd falsifisert mye og en som ikke har prøvd så mye, men er ny. Ingen av teoriene har blitt falsifisert. Hvis man da tenker seg at man velger det ene alternativet, kan man ikke ha det andre alternativet [@vassend2023b]. Dersom jeg skulle tatt et slikt valg ville begrunnelsen vært rasjonell. Jeg ville valgt det alternativet som etter fornuft virker som det beste alternativet. Dette tenker jeg kunne vært basert på sannsynlighet. Dermed har jeg igjen kommet tilbake til problemet, vi har tatt en rasjonell beslutning. Samtidig er det etter Popper kommet andre tilnærminger som prøver å løse induksjonsproblemet, som bayesianisme og abduktivisme. Men likevel så lykkes man ikke helt med å komme utenom det. Konklusjonen blir at man ikke klarer å komme helt utenom induksjonsproblemet, og tilnærmingen til Popper kommer heller ikke helt utenom problemet.

## Referanser
